export const PATCH_INSERT_NODE = 'PATCH_INSERT_NODE';
export const PATCH_REPLACE_NODE = 'PATCH_REPLACE_NODE';
export const PATCH_REMOVE_NODE = 'PATCH_REMOVE_NODE';
export const PATCH_TEXT_NODE = 'PATCH_TEXT_NODE';
export const PATCH_PROPS_NODE = 'PATCH_PROPS_NODE';
