module.exports.PATCH_INSERT_NODE = 'PATCH_INSERT_NODE';
module.exports.PATCH_REPLACE_NODE = 'PATCH_REPLACE_NODE';
module.exports.PATCH_REMOVE_NODE = 'PATCH_REMOVE_NODE';
module.exports.PATCH_TEXT_NODE = 'PATCH_TEXT_NODE';
module.exports.PATCH_PROPS_NODE = 'PATCH_PROPS_NODE';
